export const AI_LOG_ENTRIES = [
  {
    id: 'ai1',
    timestamp: '2025-05-22 09:14:32',
    file: 'Cotizacion_CementosAndinos_Miralindo.pdf',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Cotizaciones / Edificio Miralindo',
    category: 'Cotización de Proveedor',
    supplier: 'Cementos Andinos S.A.S.',
    project: 'Edificio Miralindo',
    confidence: 0.96,
    tags: ['cotización', 'cemento', 'proveedor'],
    status: 'success',
  },
  {
    id: 'ai2',
    timestamp: '2025-05-22 09:12:18',
    file: 'Contrato_AcerosDelCentro_Portal.pdf',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Contratos / Portal del Río',
    category: 'Contrato de Servicios',
    supplier: 'Aceros del Centro Ltda.',
    project: 'Portal del Río',
    confidence: 0.94,
    tags: ['contrato', 'acero', 'servicios'],
    status: 'success',
  },
  {
    id: 'ai3',
    timestamp: '2025-05-22 09:10:05',
    file: 'Plano_Hidraulico_CasaLoma_Rev2.dwg',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Planos / CasaLoma',
    category: 'Instalaciones Hidráulicas',
    supplier: null,
    project: 'Conjunto Residencial CasaLoma',
    confidence: 0.91,
    tags: ['planos', 'hidráulica', 'DWG'],
    status: 'success',
  },
  {
    id: 'ai4',
    timestamp: '2025-05-21 17:45:20',
    file: 'Informe_Avance_Semanal_ReservaBosque.docx',
    action: 'Revisión requerida',
    fromFolder: 'Sin clasificar',
    toFolder: 'Pendiente de revisión',
    category: 'Informe de Avance',
    supplier: null,
    project: 'Reserva del Bosque',
    confidence: 0.71,
    tags: ['informe', 'avance', 'semanal'],
    status: 'review',
  },
  {
    id: 'ai5',
    timestamp: '2025-05-21 16:30:11',
    file: 'Evaluacion_TransporteAndino_CasaLoma.pdf',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Evaluaciones / CasaLoma',
    category: 'Evaluación de Proveedor',
    supplier: 'Transporte Andino S.A.S.',
    project: 'Conjunto Residencial CasaLoma',
    confidence: 0.93,
    tags: ['evaluación', 'transporte', 'proveedor'],
    status: 'success',
  },
  {
    id: 'ai6',
    timestamp: '2025-05-21 15:15:44',
    file: 'Licencia_Uso_Suelo_TorreAlameda.pdf',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Licencias y permisos / Torre Alameda',
    category: 'Licencia y Permisos',
    supplier: null,
    project: 'Torre Alameda',
    confidence: 0.98,
    tags: ['licencia', 'uso de suelo', 'Fusagasugá'],
    status: 'success',
  },
  {
    id: 'ai7',
    timestamp: '2025-05-20 11:22:33',
    file: 'Acta_Reunion_Comite_Mayo.docx',
    action: 'Revisión requerida',
    fromFolder: 'Sin clasificar',
    toFolder: 'Pendiente de revisión',
    category: 'Acta de Reunión',
    supplier: null,
    project: 'Indefinido',
    confidence: 0.68,
    tags: ['acta', 'comité', 'reunión'],
    status: 'review',
  },
  {
    id: 'ai8',
    timestamp: '2025-05-20 10:05:17',
    file: 'Presupuesto_Actualizacion_Portal_Rio.xlsx',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Presupuestos / Portal del Río',
    category: 'Presupuesto de Obra',
    supplier: null,
    project: 'Portal del Río',
    confidence: 0.95,
    tags: ['presupuesto', 'actualización', 'costos'],
    status: 'success',
  },
  {
    id: 'ai9',
    timestamp: '2025-05-19 14:40:09',
    file: 'Cronograma_TorreAlameda_v1.xlsx',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Cronogramas / Torre Alameda',
    category: 'Cronograma de Obra',
    supplier: null,
    project: 'Torre Alameda',
    confidence: 0.97,
    tags: ['cronograma', 'hitos', 'v1'],
    status: 'success',
  },
  {
    id: 'ai10',
    timestamp: '2025-05-19 09:55:28',
    file: 'Cotizacion_HidroSoluciones_Portal.pdf',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Cotizaciones / Portal del Río',
    category: 'Cotización de Proveedor',
    supplier: 'HidroSoluciones Ltda.',
    project: 'Portal del Río',
    confidence: 0.92,
    tags: ['cotización', 'hidráulica', 'proveedor'],
    status: 'success',
  },
  {
    id: 'ai11',
    timestamp: '2025-05-18 16:20:55',
    file: 'Orden_Compra_Maquinaria_CasaLoma.pdf',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Compras / CasaLoma',
    category: 'Orden de Compra',
    supplier: 'Maquinaria Capital S.A.',
    project: 'Conjunto Residencial CasaLoma',
    confidence: 0.94,
    tags: ['compra', 'maquinaria', 'orden'],
    status: 'success',
  },
  {
    id: 'ai12',
    timestamp: '2025-05-18 08:30:12',
    file: 'Plano_Fachada_ReservaBosque_Final.pdf',
    action: 'Clasificado automáticamente',
    fromFolder: 'Sin clasificar',
    toFolder: 'Planos / Reserva del Bosque',
    category: 'Diseño Arquitectónico',
    supplier: null,
    project: 'Reserva del Bosque',
    confidence: 0.88,
    tags: ['planos', 'fachada', 'final'],
    status: 'success',
  },
]

export const AI_PROCESSING_STEPS = [
  'Escaneando documentos sin clasificar...',
  'Analizando contenido y metadata...',
  'Identificando proveedores relacionados...',
  'Detectando proyectos asociados...',
  'Clasificando por categoría documental...',
  'Extrayendo tags y palabras clave...',
  'Organizando en carpetas de destino...',
  'Generando resumen de organización...',
]
