export const SUPPLIERS = [
  {
    id: 's1',
    name: 'Cementos Andinos S.A.S.',
    category: 'Cemento',
    nit: '900.123.456-1',
    contact: 'Laura Méndez',
    email: 'ventas@cementosandinos.co',
    phone: '+57 310 555 0101',
    city: 'Bogotá D.C.',
    rating: 4.8,
    ratingTime: 4.9,
    ratingCompliance: 4.7,
    ratingQuality: 4.8,
    riskLevel: 'low',
    projects: ['p1', 'p3', 'p5'],
    documentsCount: 12,
    certifications: ['ISO 9001:2015', 'RETIE'],
    delays: 0,
    claims: 0,
    lastActivity: '2025-05-15',
    notes: 'Proveedor prioritario. Excelente cumplimiento y calidad sostenida.',
    activeContracts: 2,
  },
  {
    id: 's2',
    name: 'Aceros del Centro Ltda.',
    category: 'Acero',
    nit: '800.456.789-2',
    contact: 'Hernán Vargas',
    email: 'comercial@acerosdel centro.co',
    phone: '+57 314 222 3344',
    city: 'Girardot',
    rating: 4.5,
    ratingTime: 4.3,
    ratingCompliance: 4.6,
    ratingQuality: 4.6,
    riskLevel: 'low',
    projects: ['p1', 'p2', 'p4'],
    documentsCount: 9,
    certifications: ['ISO 9001:2015'],
    delays: 1,
    claims: 0,
    lastActivity: '2025-05-10',
    notes: 'Buen proveedor, leve retraso en entrega de marzo. Resuelto.',
    activeContracts: 3,
  },
  {
    id: 's3',
    name: 'Concreto Total S.A.',
    category: 'Concreto',
    nit: '901.234.567-3',
    contact: 'Mónica Patiño',
    email: 'pedidos@concretototal.com.co',
    phone: '+57 311 789 0012',
    city: 'Bogotá D.C.',
    rating: 4.2,
    ratingTime: 4.0,
    ratingCompliance: 4.4,
    ratingQuality: 4.2,
    riskLevel: 'low',
    projects: ['p1', 'p3', 'p6'],
    documentsCount: 8,
    certifications: ['ISO 14001'],
    delays: 2,
    claims: 1,
    lastActivity: '2025-05-08',
    notes: 'Buen proveedor para volúmenes grandes. Revisar tiempos de entrega.',
    activeContracts: 2,
  },
  {
    id: 's4',
    name: 'Transporte Andino S.A.S.',
    category: 'Transporte',
    nit: '700.987.654-4',
    contact: 'Ricardo Ospina',
    email: 'logistica@transporteandino.co',
    phone: '+57 320 111 2233',
    city: 'Facatativá',
    rating: 3.6,
    ratingTime: 3.2,
    ratingCompliance: 3.8,
    ratingQuality: 3.8,
    riskLevel: 'medium',
    projects: ['p2', 'p4', 'p5'],
    documentsCount: 7,
    certifications: [],
    delays: 4,
    claims: 2,
    lastActivity: '2025-04-30',
    notes: '4 retrasos reportados en Q1 2025. Impacto medio en cronograma de CasaLoma.',
    activeContracts: 1,
  },
  {
    id: 's5',
    name: 'Eléctricas Nova S.A.S.',
    category: 'Instalaciones eléctricas',
    nit: '901.111.222-5',
    contact: 'Andrés Lozano',
    email: 'contacto@electricasnova.co',
    phone: '+57 315 444 5566',
    city: 'Bogotá D.C.',
    rating: 3.9,
    ratingTime: 4.1,
    ratingCompliance: 3.8,
    ratingQuality: 3.8,
    riskLevel: 'medium',
    projects: ['p3', 'p6'],
    documentsCount: 6,
    certifications: ['RETIE', 'RETILAP'],
    delays: 2,
    claims: 1,
    lastActivity: '2025-05-12',
    notes: 'Cumple especificaciones técnicas. Revisar recursos en próximo contrato.',
    activeContracts: 2,
  },
  {
    id: 's6',
    name: 'HidroSoluciones Ltda.',
    category: 'Instalaciones hidráulicas',
    nit: '800.333.444-6',
    contact: 'Sandra Pineda',
    email: 'info@hidrosoluciones.co',
    phone: '+57 317 666 7788',
    city: 'Chía',
    rating: 4.1,
    ratingTime: 4.0,
    ratingCompliance: 4.2,
    ratingQuality: 4.1,
    riskLevel: 'low',
    projects: ['p3', 'p5'],
    documentsCount: 5,
    certifications: ['ISO 9001:2015'],
    delays: 1,
    claims: 0,
    lastActivity: '2025-05-05',
    notes: 'Proveedor confiable para redes hidráulicas y sanitarias.',
    activeContracts: 1,
  },
  {
    id: 's7',
    name: 'Seguridad Integral S.A.',
    category: 'Seguridad',
    nit: '860.111.999-7',
    contact: 'Luis Bermúdez',
    email: 'contratos@seguridadintegral.co',
    phone: '+57 321 000 1122',
    city: 'Bogotá D.C.',
    rating: 2.8,
    ratingTime: 2.5,
    ratingCompliance: 3.0,
    ratingQuality: 2.9,
    riskLevel: 'high',
    projects: ['p1', 'p2'],
    documentsCount: 4,
    certifications: ['SG-SST'],
    delays: 5,
    claims: 3,
    lastActivity: '2025-04-15',
    notes: 'ALERTA: 5 retrasos y 3 reclamos activos. Revisar continuidad del contrato.',
    activeContracts: 1,
  },
  {
    id: 's8',
    name: 'Carpintería del Norte S.A.S.',
    category: 'Carpintería',
    nit: '900.777.888-8',
    contact: 'María Castillo',
    email: 'ventas@carpinteriadelnorte.co',
    phone: '+57 316 555 6677',
    city: 'Zipaquirá',
    rating: 3.3,
    ratingTime: 3.1,
    ratingCompliance: 3.4,
    ratingQuality: 3.4,
    riskLevel: 'medium',
    projects: ['p6'],
    documentsCount: 3,
    certifications: [],
    delays: 3,
    claims: 1,
    lastActivity: '2025-04-28',
    notes: 'Calidad aceptable. Tiempos de entrega irregulares. En seguimiento.',
    activeContracts: 1,
  },
  {
    id: 's9',
    name: 'Acabados Premium Ltda.',
    category: 'Acabados',
    nit: '901.555.666-9',
    contact: 'Diana Moreno',
    email: 'proyectos@acabadospremium.co',
    phone: '+57 312 333 4455',
    city: 'Bogotá D.C.',
    rating: 2.1,
    ratingTime: 1.9,
    ratingCompliance: 2.2,
    ratingQuality: 2.2,
    riskLevel: 'high',
    projects: ['p3'],
    documentsCount: 4,
    certifications: [],
    delays: 7,
    claims: 4,
    lastActivity: '2025-03-30',
    notes: 'CRÍTICO: Múltiples incumplimientos. 4 reclamos abiertos. Calidad bajo estándar.',
    activeContracts: 0,
  },
  {
    id: 's10',
    name: 'Maquinaria Capital S.A.',
    category: 'Maquinaria',
    nit: '800.222.333-0',
    contact: 'Carlos Ríos',
    email: 'alquiler@maquinariacapital.co',
    phone: '+57 318 999 0011',
    city: 'Mosquera',
    rating: 4.3,
    ratingTime: 4.5,
    ratingCompliance: 4.2,
    ratingQuality: 4.2,
    riskLevel: 'low',
    projects: ['p1', 'p2', 'p4', 'p5'],
    documentsCount: 10,
    certifications: ['ISO 9001:2015'],
    delays: 1,
    claims: 0,
    lastActivity: '2025-05-18',
    notes: 'Proveedor estratégico para maquinaria pesada. Disponibilidad garantizada.',
    activeContracts: 4,
  },
]

export function getRiskColor(rating) {
  if (rating >= 4.0) return 'green'
  if (rating >= 3.0) return 'amber'
  return 'red'
}

export function getRiskLabel(level) {
  const labels = { low: 'Bajo', medium: 'Medio', high: 'Alto' }
  return labels[level] || level
}
